image: maven:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - package
  - deploy

# Build Stage
build-job:       
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn clean #install
#    - mvn validate
    # - echo "Starting up server"
    # - bash runServer.sh &  # Start server in background
    - sleep 5
    # - mvn install
    - echo "Startign complile process"
    - mvn compile
    - echo "Compile complete."

# Unit Test Stage
unit-test-job:   
  stage: test   
  script:
    - echo "Running unit tests..."
    - mvn '-Dtest=ClientTests.*Test' test
    - mvn '-Dtest=ServerTests.*Test' test
    - echo "All unit tests ran successfully."

# Acceptance Test Stage
acceptance-test-job:   
  stage: test    
  script:
    - echo "Running acceptance tests..."
    - bash runServer.sh &  # Start server in background
    - SERVER_PID=$!         # Capture server PID to stop it later
    - echo "Waiting for server to start..."
    - sleep 10              # Give the server enough time to fully start
    - mvn '-Dtest=AcceptanceTests.*Test' test
    - echo "Stopping server after acceptance tests..."
    - kill $SERVER_PID       # Stop server after tests
    - echo "No acceptance test issues found."

# Package Stage
package-job:   
  stage: package    
  script:
    - echo "Packaging code..."
    - bash runServer.sh &  # Start server in background
    - SERVER_PID=$!         # Capture server PID to stop it later
    - echo "Waiting for server to start..."
    - sleep 10              # Give the server enough time to fully start
    - mvn package
    - echo "Successfully packaged."
    - mvn verify
    - echo "Stopping server after packaging..."
    - kill $SERVER_PID       # Stop server after packaging
    - echo "No package issues found."

# Deploy Stage
deploy-job:      
  stage: deploy  
  environment: production
  script:
    - echo "Deploying application..."
    - bash runServer.sh &  # Start server in background
    - SERVER_PID=$!         # Capture server PID to stop it later
    - echo "Waiting for server to start..."
    - sleep 10              # Give the server enough time to fully start
    - mvn deploy
    - echo "Stopping server after deployment..."
    - kill $SERVER_PID       # Stop server after deployment
    - echo "Application successfully deployed."
